//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilliingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractBillingPlanBindingSet = new HashSet<ContractBillingPlanBindingSet>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractCloseDate { get; set; }
        public int TerminalId { get; set; }
    
        public virtual Client ClientSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractBillingPlanBindingSet> ContractBillingPlanBindingSet { get; set; }
        public virtual Terminal TerminalSet { get; set; }
    }
}
